import type { CategorySlug } from '@/lib/listings-data'

export interface ShowcaseExample {
  origin: string
  title: string
  spec: string
}

export interface CategoryShowcaseContent {
  slug: CategorySlug
  eyebrow: string
  desk: string
  pitch: string
  coordinates: string[]
  examples: ShowcaseExample[]
}

export const categoryShowcaseContent: Record<CategorySlug, CategoryShowcaseContent> = {
  'cars-suvs': {
    slug: 'cars-suvs',
    eyebrow: 'LHD & RHD',
    desk: 'A dedicated desk for cars & SUVs',
    pitch: 'Curated acquisition of luxury sedans, performance coupés and SUVs in both left- and right-hand drive, sourced globally and delivered turnkey to your door.',
    coordinates: [
      'Both left-hand and right-hand drive sourcing from global markets',
      'Pre-purchase independent inspection and provenance verification',
      'Container, RoRo, and enclosed trailer transit options',
      'Customs clearance, registration support, and door delivery',
      'Concierge for bespoke specification and factory orders',
    ],
    examples: [
      { origin: 'Stuttgart, DE', title: 'Executive Saloon — LHD', spec: '6 cyl · AWD · Leather' },
      { origin: 'Munich, DE', title: 'Luxury Flagship Sedan — LHD', spec: 'V8 · Air suspension' },
      { origin: 'Yokohama, JP', title: 'Full-Size SUV — LHD', spec: 'V6 · 7-seat · 4WD' },
      { origin: 'Sindelfingen, DE', title: 'Performance Coupé — LHD', spec: 'Twin-turbo V8 · RWD' },
      { origin: 'London, UK', title: 'Compact Executive — RHD', spec: 'Diesel · 4-door' },
      { origin: 'Nagoya, JP', title: 'Heritage Saloon — RHD', spec: 'Hybrid · LHD/RHD option' },
      { origin: 'Modena, IT', title: 'Grand Tourer — LHD', spec: 'V12 · Coupé' },
      { origin: 'Durban, ZA', title: 'Off-Road SUV — RHD', spec: 'Diesel · 4×4 · Snorkel' },
      { origin: 'Crewe, UK', title: 'Hyper-SUV — LHD', spec: 'Twin-turbo V8 · Carbon' },
      { origin: 'Fremont, US', title: 'City EV — LHD', spec: 'Dual motor · 480 km' },
      { origin: 'Stuttgart, DE', title: 'Track Coupé — LHD', spec: 'Flat-6 · Manual' },
      { origin: 'Toyota City, JP', title: 'Luxury MPV — RHD', spec: 'Hybrid · 6-seat lounge' },
      { origin: 'Ota, JP', title: 'Adventure Wagon — LHD', spec: 'Boxer · AWD' },
      { origin: 'Goodwood, UK', title: 'Bespoke Limousine — LHD', spec: 'V12 · Extended wheelbase' },
      { origin: 'Hiroshima, JP', title: 'Rally-Homologation Coupé — LHD', spec: 'Turbo flat-4 · AWD' },
      { origin: 'Seoul, KR', title: 'Executive SUV — RHD', spec: 'V6 diesel · 7-seat' },
      { origin: 'Munich, DE', title: 'Open-Top Roadster — LHD', spec: 'Inline-6 · Soft-top' },
      { origin: 'Coventry, UK', title: 'Performance Sedan — RHD', spec: 'Supercharged V8' },
    ],
  },

  'commercial-fleet': {
    slug: 'commercial-fleet',
    eyebrow: 'Heavy & Light Duty',
    desk: 'A dedicated desk for commercial fleet',
    pitch: 'Trucks, trailers, buses and microbuses — procured, inspected and deployed for operators who cannot afford downtime.',
    coordinates: [
      'Tractor units, tippers, coaches and microbuses sourced globally',
      'Pre-purchase mechanical and structural inspection',
      'RoRo, flat-rack and multi-unit container transit',
      'Fleet registration, customs and destination compliance support',
      'Concierge for multi-unit fleet deployment mandates',
    ],
    examples: [
      { origin: 'Gothenburg, SE', title: 'Long-Haul Tractor Unit — LHD', spec: '13L · 500hp · 6x4' },
      { origin: 'Wörth am Rhein, DE', title: 'Distribution Tractor — LHD', spec: '12.8L · 449hp' },
      { origin: 'Munich, DE', title: 'Heavy Duty Truck — LHD', spec: '16.2L · 640hp · 4x2' },
      { origin: 'Neu-Ulm, DE', title: 'Luxury Touring Coach — LHD', spec: '49-seat · Diesel' },
      { origin: 'Toyota City, JP', title: 'Premium Microbus — RHD', spec: '30-seat · Diesel' },
      { origin: 'Zhengzhou, CN', title: 'Low-Floor City Bus — LHD', spec: 'Hybrid · 90-pax' },
      { origin: 'North Carolina, US', title: 'Vocational Tractor Unit — LHD', spec: '14.8L · 505hp' },
      { origin: 'Texas, US', title: 'Long-Haul Flagship — LHD', spec: '15L · 605hp' },
      { origin: 'Düsseldorf, DE', title: 'Box Body Van — LHD', spec: '2.0L Diesel' },
      { origin: 'Hino, JP', title: 'Construction Tipper — RHD', spec: '6x4 · 20m³' },
      { origin: 'Plauen, DE', title: 'Panoramic Coach — LHD', spec: '49-seat · Diesel' },
      { origin: 'Sainte-Claire, CA', title: 'Luxury Coach — LHD', spec: '56-seat · Diesel' },
      { origin: 'Werlte, DE', title: 'Refrigerated Trailer', spec: '13.6m · -25°C' },
      { origin: 'Alabama, US', title: 'Extendable Lowboy', spec: '55-Ton Capacity' },
      { origin: 'Kaatsheuvel, NL', title: 'Car Carrier Trailer', spec: '9-Vehicle · Extendable' },
      { origin: 'Sakarya, TR', title: 'Midibus — LHD', spec: '25-seat · Diesel' },
      { origin: 'Falkirk, UK', title: 'Double Decker Bus — RHD', spec: '87-seat' },
      { origin: 'Kentucky, US', title: 'Terminal Yard Tractor — LHD', spec: '5th Wheel · Shunt' },
    ],
  },

  'heavy-machinery': {
    slug: 'heavy-machinery',
    eyebrow: 'Industrial Assets',
    desk: 'A dedicated desk for heavy machinery',
    pitch: 'Excavators, loaders, cranes and earthmoving equipment — sourced to spec, certified and mobilized to any jobsite on the map.',
    coordinates: [
      'Excavators, loaders, cranes and specialist equipment sourced globally',
      'Independent mechanical inspection and operating-hour verification',
      'Breakbulk, flat-rack and heavy-lift transit engineering',
      'Import compliance, jobsite delivery and rigging coordination',
      'Concierge for multi-unit fleet mobilization mandates',
    ],
    examples: [
      { origin: 'Illinois, US', title: 'Crawler Excavator — 20-Ton', spec: '1.2m³ Bucket' },
      { origin: 'Tokyo, JP', title: 'Crawler Excavator — 21-Ton', spec: 'Tier 4 · Fuel Efficient' },
      { origin: 'Ehingen, DE', title: 'Mobile Crane — 90-Ton', spec: 'Telescopic · 5-Axle' },
      { origin: 'Illinois, US', title: 'Wheel Loader', spec: '3.4m³ Bucket · Z-Bar' },
      { origin: 'Staffordshire, UK', title: 'Backhoe Loader', spec: '4x4 · Extendable Dipper' },
      { origin: 'Braås, SE', title: 'Articulated Dump Truck — 39-Ton', spec: '6x6 Payload' },
      { origin: 'Ancenis, FR', title: 'Rotating Telehandler', spec: 'Lift 32m · 5.5-Ton' },
      { origin: 'Windhagen, DE', title: 'Cold Milling Machine', spec: '2.2m Width' },
      { origin: 'Xuzhou, CN', title: 'All-Terrain Crane — 250-Ton', spec: 'Heavy Lift' },
      { origin: 'Iowa, US', title: 'Motor Grader', spec: 'Moldboard · AWD' },
      { origin: 'Straubing, DE', title: 'Material Handler — 30-Ton', spec: 'Scrap & Recycling' },
      { origin: 'Takamatsu, JP', title: 'Rough Terrain Crane — 100-Ton', spec: 'Compact Footprint' },
      { origin: 'Wisconsin, US', title: 'Crawler Bulldozer', spec: 'Semi-U Blade' },
      { origin: 'Boppard, DE', title: 'Vibratory Soil Compactor', spec: '13-Ton Single Drum' },
      { origin: 'Changsha, CN', title: 'Crawler Crane — 400-Ton', spec: 'Heavy Infrastructure' },
      { origin: 'Motherwell, UK', title: 'Articulated Dump Truck — 38-Ton', spec: '6x6' },
      { origin: 'Indiana, US', title: 'Standby Diesel Generator', spec: '1100kVA' },
      { origin: 'Pennsylvania, US', title: 'All-Terrain Crane — 250-Ton', spec: 'Multi-Axle' },
    ],
  },

  marine: {
    slug: 'marine',
    eyebrow: 'Marine Division',
    desk: 'A dedicated desk for marine assets',
    pitch: 'Motor yachts, sport cruisers and commercial watercraft — acquired, surveyed and shipped across oceans with white-glove marine logistics.',
    coordinates: [
      'Motor yachts, sport cruisers and commercial vessels sourced globally',
      'Independent marine survey and condition verification',
      'Float-on/float-off, cradle and containerized transit options',
      'Flagging, registration and destination marina coordination',
      'Concierge for bespoke and custom-build vessel mandates',
    ],
    examples: [
      { origin: 'Poole, UK', title: 'Sport Motor Yacht — 22.7m', spec: '3 Cabins · 30 Knots' },
      { origin: 'Avigliana, IT', title: 'Flybridge Motor Yacht — 27m', spec: '4 Cabins · IPS Drives' },
      { origin: 'Plymouth, UK', title: 'Superyacht Class — 29m', spec: 'Luxury Configuration' },
      { origin: 'Sarnico, IT', title: 'Sport Coupé — 20.9m', spec: 'Performance Hull' },
      { origin: 'Antalya, TR', title: 'Explorer Yacht — 26m', spec: 'Long Range' },
      { origin: 'Viareggio, IT', title: 'Motor Yacht — 26m', spec: '4 Cabins' },
      { origin: 'Saint-Gilles-Croix-de-Vie, FR', title: 'Sailing Yacht — 15.7m', spec: '3 Cabins' },
      { origin: 'Bordeaux, FR', title: 'Sailing Catamaran — 15.5m', spec: 'Charter Configuration' },
      { origin: 'Cape Town, ZA', title: 'Power Catamaran — 16m', spec: 'Twin Hull' },
      { origin: 'Florida, US', title: 'Center Console — 11.6m', spec: 'Dual Console' },
      { origin: 'North Carolina, US', title: 'Sport Fisher — 25m', spec: 'Tuna Tower' },
      { origin: 'New Jersey, US', title: 'Convertible — 25m', spec: 'Enclosed Bridge' },
      { origin: 'La Rochelle, FR', title: 'Luxury RIB — 7.6m', spec: 'Rigid Inflatable' },
      { origin: 'Ryde, UK', title: 'Tender — 4.5m', spec: 'Jet Drive' },
      { origin: 'Valcourt, CA', title: 'Personal Watercraft', spec: '325hp' },
      { origin: 'Shizuoka, JP', title: 'Sport Boat', spec: '3-Seat' },
      { origin: 'North Carolina, US', title: 'Motor Yacht — 27.4m', spec: 'Panorama Configuration' },
      { origin: 'Slagelse, DK', title: 'Open Sport Boat — 13.4m', spec: 'Day Cruiser' },
    ],
  },

  mobility: {
    slug: 'mobility',
    eyebrow: 'Two-Wheeler & Mobility',
    desk: 'A dedicated desk for mobility assets',
    pitch: 'Performance motorcycles, urban scooters and personal mobility platforms — sourced, tuned and crated for pristine global delivery.',
    coordinates: [
      'Sport, adventure, touring and electric motorcycles sourced globally',
      'Pre-purchase inspection and provenance verification',
      'Crated air freight and consolidated container options',
      'Registration support and destination compliance',
      'Concierge for multi-unit fleet and collection mandates',
    ],
    examples: [
      { origin: 'Bologna, IT', title: 'Superbike — 1103cc', spec: 'V4 · 214hp' },
      { origin: 'Mattighofen, AT', title: 'Naked Sport — 1301cc', spec: 'V-Twin · 180hp' },
      { origin: 'Berlin, DE', title: 'Adventure Tourer — 1254cc', spec: 'Boxer · AWD Option' },
      { origin: 'Wisconsin, US', title: 'Touring Cruiser — 1923cc', spec: 'V-Twin' },
      { origin: 'Shizuoka, JP', title: 'Superbike — 998cc', spec: 'Inline-4 · 200hp' },
      { origin: 'Hinckley, UK', title: 'Naked Roadster — 1160cc', spec: 'Triple' },
      { origin: 'Kumamoto, JP', title: 'Superbike — 999cc', spec: '217hp' },
      { origin: 'Iowa, US', title: 'Touring Cruiser — 1890cc', spec: 'V-Twin' },
      { origin: 'Varese, IT', title: 'Naked Sport — 998cc', spec: 'Inline-4 · 208hp' },
      { origin: 'Mandello del Lario, IT', title: 'Sport Tourer — 1042cc', spec: 'Twin' },
      { origin: 'Chennai, IN', title: 'Adventure — 452cc', spec: 'Single' },
      { origin: 'Pontedera, IT', title: 'Urban Scooter — 150cc', spec: 'Automatic' },
      { origin: 'Kaohsiung, TW', title: 'Maxi Scooter — 550cc', spec: 'Touring' },
      { origin: 'California, US', title: 'Electric Motorcycle', spec: '322km Range' },
      { origin: 'Beijing, CN', title: 'Electric Scooter', spec: '70km Range' },
      { origin: 'Wisconsin, US', title: 'Electric Mountain Bike', spec: 'E-MTB' },
      { origin: 'Shizuoka, JP', title: 'Maxi Scooter — 562cc', spec: 'Touring' },
      { origin: 'Hangzhou, CN', title: 'Adventure — 799cc', spec: 'Twin' },
    ],
  },

  'parts-customization': {
    slug: 'parts-customization',
    eyebrow: 'Parts & Atelier',
    desk: 'A dedicated desk for parts & customization',
    pitch: 'OEM and performance parts, bespoke tuning, accessories and full custom modifications — engineered and dispatched worldwide.',
    coordinates: [
      'OEM and aftermarket performance parts sourced globally',
      'Brand and specification verification before dispatch',
      'Air freight and consolidated container shipping options',
      'Import compliance and destination customs support',
      'Concierge for bespoke fabrication and atelier mandates',
    ],
    examples: [
      { origin: 'Bergamo, IT', title: 'Big Brake Kit', spec: '6-Piston · 410mm Rotor' },
      { origin: 'California, US', title: 'Forged Wheel Set', spec: '1-Piece · 21"' },
      { origin: 'Fichtenberg, DE', title: 'Coilover Suspension', spec: 'Adjustable' },
      { origin: 'Ivančna Gorica, SI', title: 'Titanium Exhaust System', spec: 'Full Titanium' },
      { origin: 'Kirchheim, DE', title: 'Bucket Seats', spec: 'FIA Approved' },
      { origin: 'Brand, DE', title: 'Widebody Conversion Kit', spec: 'Fiberglass · +60mm' },
      { origin: 'Stetten, DE', title: 'Carbon Body Kit', spec: 'Pre-Preg Carbon' },
      { origin: 'Leonberg, DE', title: 'Aerodynamic Package', spec: 'Track-Tested' },
      { origin: 'Schiltach, DE', title: 'Forged Wheels', spec: '1-Piece · Motorsport' },
      { origin: 'Wiltshire, UK', title: 'Cat-Back Exhaust', spec: 'Valved · Stainless' },
      { origin: 'Florida, US', title: 'Performance ECU Package', spec: 'Stage 1 · +80hp' },
      { origin: 'Nagano, JP', title: 'Widebody Kit', spec: 'Full Fiberglass' },
      { origin: 'Milan, IT', title: 'Bespoke Interior Retrim', spec: 'Hand-Stitched Leather' },
      { origin: 'Osaka, JP', title: 'Roll Cage', spec: 'CrMo Bolt-In' },
      { origin: 'Rolle, CH', title: 'Performance Turbocharger', spec: 'Ball-Bearing' },
      { origin: 'Aubervilliers, FR', title: 'Racing Engine Oil', spec: 'Ester-Core' },
      { origin: 'Tamworth, UK', title: 'Monobloc Brake Kit', spec: '6-Piston' },
      { origin: 'Chiba, JP', title: 'Adjustable GT Wing', spec: 'Carbon Fiber' },
    ],
  },
}